FROM python:3.9

# Install supervisor
RUN apt-get update && apt-get install -y supervisor

RUN mkdir app

RUN cd app

WORKDIR /app

COPY .fs .

RUN pip install --upgrade flask-setup
RUN fs install

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    poppler-utils \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY . .

# TODO: Add all your environment variables here
ARG DATABASE_URI
ENV DATABASE_URI=${DATABASE_URI}

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ARG PINECONE_API_KEY
ENV PINECONE_API_KEY=${PINECONE_API_KEY}

ARG TWILIO_ACCOUNT_SID
ENV TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}

ARG TWILIO_AUTH_TOKEN
ENV TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}

ARG TWILIO_PHONE_NUMBER
ENV TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}

ARG AFRICASTALKING_API_KEY
ENV AFRICASTALKING_API_KEY=${AFRICASTALKING_API_KEY}

ARG AFRICASTALKING_USERNAME
ENV AFRICASTALKING_USERNAME=${AFRICASTALKING_USERNAME}

ARG SPACE_REGION
ENV SPACE_REGION=${SPACE_REGION}

ARG SPACE_NAME
ENV SPACE_NAME=${SPACE_NAME}

ARG SPACE_KEY
ENV SPACE_KEY=${SPACE_KEY}

ARG SPACE_SECRET
ENV SPACE_SECRET=${SPACE_SECRET}

ARG SPACE_ENDPOINT
ENV SPACE_ENDPOINT=${SPACE_ENDPOINT}

ARG SPACE_EDGE_ENDPOINT
ENV SPACE_EDGE_ENDPOINT=${SPACE_EDGE_ENDPOINT}

ARG CELERY_BROKER_URL
ENV CELERY_BROKER_URL=${CELERY_BROKER_URL}

ARG result_backend
ENV result_backend=${result_backend}

ARG MAIL_SERVER
ENV MAIL_SERVER=${MAIL_SERVER}

ARG MAIL_PORT
ENV MAIL_PORT=${MAIL_PORT}

ARG MAIL_USERNAME
ENV MAIL_USERNAME=${MAIL_USERNAME}

ARG MAIL_PASSWORD
ENV MAIL_PASSWORD=${MAIL_PASSWORD}

ARG APP_SECRET
ENV APP_SECRET=${APP_SECRET}

ARG FLASK_DEBUG
ENV FLASK_DEBUG=${FLASK_DEBUG}

RUN flask db upgrade

RUN python manage.py


EXPOSE 80

CMD bash -c "supervisord -c supervisord.conf"