"""Add analytics tables

Revision ID: 3043885539c4
Revises: d2219fbbf001
Create Date: 2025-06-27 22:57:36.641064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3043885539c4'
down_revision = 'd2219fbbf001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query_analytics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_keyword')
    op.drop_table('query_analytics')
    # ### end Alembic commands ###
