"""empty message

Revision ID: 33796eaadde8
Revises: 9191f4b7014f
Create Date: 2025-08-31 13:48:51.870139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect as _inspect


# revision identifiers, used by Alembic.
revision = '33796eaadde8'
down_revision = '9191f4b7014f'
branch_labels = None
depends_on = None

def _insp():
    bind = op.get_bind()
    return _inspect(bind)

def _has_table(name: str) -> bool:
    return name in _insp().get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_table('query_keyword'):
        op.drop_table('query_keyword')
        
    if _has_table('query_analytics'):
        op.drop_table('query_analytics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_analytics',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('query_analytics_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='query_analytics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='query_analytics_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('query_keyword',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('query_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['query_analytics.id'], name='query_keyword_query_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='query_keyword_pkey')
    )
    # ### end Alembic commands ###
