"""empty message

Revision ID: 481e9c65ac52
Revises: 7f09056fd03f
Create Date: 2024-09-30 19:53:17.390011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481e9c65ac52'
down_revision = '7f09056fd03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ussd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('previous', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_set', sa.Boolean(), nullable=True))
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('numbers', schema=None) as batch_op:
        batch_op.alter_column('area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_set')

    op.drop_table('ussd')
    # ### end Alembic commands ###
