"""added shortcode_id and whatsapp_number id  when creating file

Revision ID: 4ab17b2c2c15
Revises: b4a3f87fa29e
Create Date: 2026-03-29 13:51:21.276982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab17b2c2c15'
down_revision = 'b4a3f87fa29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortcode_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'shortcodes', ['shortcode_id'], ['id'])
        batch_op.create_foreign_key(None, 'whatsapp__number', ['whatsapp_number_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('whatsapp_number_id')
        batch_op.drop_column('shortcode_id')

    # ### end Alembic commands ###
