"""empty message

Revision ID: a4381ecfc972
Revises: d7ae120a43af
Create Date: 2025-04-18 15:29:58.296716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4381ecfc972'
down_revision = 'd7ae120a43af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['company_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
