"""empty message

Revision ID: b4a3f87fa29e
Revises: e624abbe9fdf
Create Date: 2026-03-28 12:56:44.768619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a3f87fa29e'
down_revision = 'e624abbe9fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('files_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_unique_constraint('files_name_key', ['name'])

    # ### end Alembic commands ###
