"""Add CreditUsage model and update CreditTransaction

Revision ID: ba87a27e78d4
Revises: 9eecb7911adc
Create Date: 2025-05-30 21:09:15.003845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba87a27e78d4'
down_revision = '9eecb7911adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('is_refunded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False))

    op.drop_table('credit_usage')
    # ### end Alembic commands ###
