"""added file url to files table

Revision ID: cd39ba4a1cd9
Revises: 4ab17b2c2c15
Create Date: 2026-03-29 15:09:46.656652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd39ba4a1cd9'
down_revision = '4ab17b2c2c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
