"""renamed content field to message in messages blueprint

Revision ID: d07bb44dccac
Revises: 4d0afd9b6d2b
Create Date: 2024-09-12 22:07:34.706940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07bb44dccac'
down_revision = '4d0afd9b6d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('messages_areas_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'areas', ['area_id'], ['id'])
        batch_op.drop_column('content')
        batch_op.drop_column('areas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('areas', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_areas_fkey', 'areas', ['areas'], ['id'])
        batch_op.drop_column('area_id')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
