"""add_transaction_type_to_credit_transaction

Revision ID: d2219fbbf001
Revises: ba87a27e78d4
Create Date: 2025-05-31 13:29:59.280157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2219fbbf001'
down_revision = 'ba87a27e78d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
