"""empty message

Revision ID: d7ae120a43af
Revises: 481e9c65ac52
Create Date: 2024-11-21 18:14:29.657924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ae120a43af'
down_revision = '481e9c65ac52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('files_weaviate_class_key', type_='unique')
        batch_op.drop_column('weaviate_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaviate_class', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('files_weaviate_class_key', ['weaviate_class'])

    # ### end Alembic commands ###
