"""empty message

Revision ID: ddbbc4196e19
Revises: 33796eaadde8
Create Date: 2026-03-25 15:29:51.650732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbbc4196e19'
down_revision = '33796eaadde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
