"""empty message

Revision ID: e624abbe9fdf
Revises: ddbbc4196e19
Create Date: 2026-03-25 15:49:36.094974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e624abbe9fdf'
down_revision = 'ddbbc4196e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_company_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_company_name_key', ['company_name'])

    # ### end Alembic commands ###
